# Copyright 2020 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

username: admin
password: NokiaSrl1!
port: 9339
timeout: 10s
skip-verify: true
encoding: json_ietf

targets:
  172.18.0.54:
  172.18.0.51:
  172.18.0.52:

subscriptions:
  all:
    paths:
      - /
    mode: stream
    stream-mode: sample
    sample-interval: 5s



outputs:
  prom:
    type: prometheus
    listen: :9273
    path: /metrics
    metric-prefix: gnmic
    append-subscription-name: true
    export-timestamps: true
    debug: false
    event-processors:
      - trim-prefixes
      - up-down-map